routes/web.php
<?php


Route::get('view_lop_with_so_luong_sinh_vien','LopController@view_lop_with_so_luong_sinh_vien');

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');

	$controller = "LopController";
	Route::group(["prefix" => "lop","as" => "lop."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
		
		Route::get("view_array_sinh_vien_by_lop/{ma}","$controller@view_array_sinh_vien_by_lop")->name("view_array_sinh_vien_by_lop");

		Route::get("thong_ke_truot_excel","$controller@thong_ke_truot_excel")->name("thong_ke_truot_excel");
		Route::get("thong_ke_truot_pdf","$controller@thong_ke_truot_pdf")->name("thong_ke_truot_pdf");
		Route::get("thong_ke_truot_chart","$controller@thong_ke_truot_chart")->name("thong_ke_truot_chart");
	});

	$controller = "SinhVienController";
	Route::group(["prefix" => "sinh_vien","as" => "sinh_vien."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");

		// form thêm bằng Excel
		Route::get("view_insert_excel","$controller@view_insert_excel")->name("view_insert_excel");
		Route::post("process_insert_excel","$controller@process_insert_excel")->name("process_insert_excel");

		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
	});

	$controller = "DiemController";
	Route::group(["prefix" => "diem","as" => "diem."],function() use ($controller){
		Route::get("","$controller@chon_lop_va_mon")->name("chon_lop_va_mon");
		Route::post("xem_diem","$controller@xem_diem")->name("xem_diem");
		Route::post("cap_nhat_diem","$controller@cap_nhat_diem")->name("cap_nhat_diem");
	});
});

Route::get('test','Controller@test');
Route::get('show','Controller@show');
Route::post('post_test','Controller@post_test')->name('post_test');

app/Models/Diem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use CoenJacobs\EloquentCompositePrimaryKeys\HasCompositePrimaryKey;

class Diem extends Model
{
	use HasCompositePrimaryKey;
    protected $table = 'diem';
    public $timestamps = false;
    public $incrementing = false;
    protected $fillable = [
    	'ma_sinh_vien',
    	'ma_mon',
    	'diem',
    ];
    protected $primaryKey = ['ma_sinh_vien','ma_mon'];
}

app/Http/Controllers/DiemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Lop;
use App\Models\Mon;
use App\Models\SinhVien;
use App\Models\Diem;
use DB;

class DiemController
{
	public function chon_lop_va_mon()
	{
		$array_lop = Lop::get();
		$array_mon = Mon::get();
		return view('diem.chon_lop_va_mon',[
			'array_lop' => $array_lop,
			'array_mon' => $array_mon,
		]);
	}
	public function xem_diem(Request $rq)
	{
		$array_lop = Lop::get();
		$array_mon = Mon::get();

		$ma_lop = $rq->ma_lop;
		$ma_mon = $rq->ma_mon;

		// $mon = Mon::where('ma',$ma_mon)->first();
		// $ten_mon = $mon->ten;
		$ten_mon = Mon::find($ma_mon)->ten;

		// sinh viên kèm điểm
		$array_sinh_vien = SinhVien::where('ma_lop',$ma_lop)->get();

		$array_diem = Diem::where('ma_lop',$ma_lop)
		->rightJoin('sinh_vien','sinh_vien.ma','diem.ma_sinh_vien')
		->where('ma_mon',$ma_mon)
		->get(['diem','sinh_vien.ma']);

		$array = [];
		foreach ($array_diem as $each) {
			$ma_sinh_vien = $each->ma;
			$diem         = $each->diem;

			$array[$ma_sinh_vien] = $diem;
		}

		return view('diem.xem_diem',[
			'array_lop'       => $array_lop,
			'array_mon'       => $array_mon,
			'array_sinh_vien' => $array_sinh_vien,
			'ma_lop'          => $ma_lop,
			'ma_mon'          => $ma_mon,
			'ten_mon'         => $ten_mon,
			'array'           => $array,
		]);
	}
	public function cap_nhat_diem(Request $rq)
	{
		$array_diem = $rq->array_diem;
		$ma_mon     = $rq->ma_mon;
		foreach ($array_diem as $ma_sinh_vien => $diem) {
			if(isset($diem)){
				Diem::updateOrCreate([
					'ma_mon'       => $ma_mon,
					'ma_sinh_vien' => $ma_sinh_vien,
				],[
					'diem' => $diem
				]);
			}
			else{
				Diem::where([
					'ma_mon'       => $ma_mon,
					'ma_sinh_vien' => $ma_sinh_vien,
				])->delete();
			}
		}
	}
}

resources/views/diem/chon_lop_va_mon.blade.php
<form action="{{ route('diem.xem_diem') }}" method="post">
	{{ csrf_field() }}
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn môn
	<select name="ma_mon">
		@foreach ($array_mon as $mon)
			<option value="{{ $mon->ma }}">
				{{ $mon->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Nhập điểm</button>
</form>

resources/views/diem/xem_diem.blade.php
<form action="{{ route('diem.xem_diem') }}" method="post">
	{{ csrf_field() }}
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}"
			@if ($ma_lop == $lop->ma)
				selected 
			@endif
			>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn môn
	<select name="ma_mon">
		@foreach ($array_mon as $mon)
			<option value="{{ $mon->ma }}"
			@if ($ma_mon == $mon->ma)
				selected 
			@endif
			>
				{{ $mon->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Nhập điểm</button>
</form>

<form action="{{ route('diem.cap_nhat_diem') }}" method="post">
	{{ csrf_field() }}
<table>
	<caption>
		Bạn đang nhập điểm cho môn: {{ $ten_mon }}
		<input type="hidden" name="ma_mon" value="{{ $ma_mon }}">
	</caption>
	<tr>
		<th>Tên sinh viên</th>
		<th>Điểm</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ten }}
			</td>
			<td>
				<input type="number" name="array_diem[{{ $sinh_vien->ma }}]" value="{{ $array[$sinh_vien->ma] ?? '' }}">
			</td>
		</tr>
	@endforeach
</table>
<button>Cập nhật điểm</button>
</form>