routes/web.php
<?php


Route::get('view_lop_with_so_luong_sinh_vien','LopController@view_lop_with_so_luong_sinh_vien');

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');

	$controller = "LopController";
	Route::group(["prefix" => "lop","as" => "lop."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
		
		Route::get("view_array_sinh_vien_by_lop/{ma}","$controller@view_array_sinh_vien_by_lop")->name("view_array_sinh_vien_by_lop");

		Route::get("thong_ke_truot_excel","$controller@thong_ke_truot_excel")->name("thong_ke_truot_excel");
		Route::get("thong_ke_truot_pdf","$controller@thong_ke_truot_pdf")->name("thong_ke_truot_pdf");
		Route::get("thong_ke_truot_chart","$controller@thong_ke_truot_chart")->name("thong_ke_truot_chart");
	});

	$controller = "SinhVienController";
	Route::group(["prefix" => "sinh_vien","as" => "sinh_vien."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");

		// form thêm bằng Excel
		Route::get("view_insert_excel","$controller@view_insert_excel")->name("view_insert_excel");
		Route::post("process_insert_excel","$controller@process_insert_excel")->name("process_insert_excel");

		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
	});

	$controller = "DiemController";
	Route::group(["prefix" => "diem","as" => "diem."],function() use ($controller){
		Route::get("","$controller@chon_lop_va_mon")->name("chon_lop_va_mon");
		Route::post("xem_diem","$controller@xem_diem")->name("xem_diem");
		Route::post("cap_nhat_diem","$controller@cap_nhat_diem")->name("cap_nhat_diem");
	});
});

Route::get('test','Controller@test');
Route::get('show','Controller@show');
Route::post('post_test','Controller@post_test')->name('post_test');

app/Models/Lop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lop extends Model
{
    protected $table = 'lop';
    public $timestamps = false;
    protected $fillable = ['ten'];
    protected $primaryKey = 'ma';
    public function array_sinh_vien()
    {
        return $this->hasMany('App\Models\SinhVien','ma_lop','ma');
    }
}

app/Http/Controllers/LopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PDF;

use App\Models\Lop;
use App\Exports\Lop\ThongKeTruotExportExcel;
use Maatwebsite\Excel\Facades\Excel;

class LopController extends Controller
{
    
    public function view_all()
    {
    	$array_lop = Lop::withCount('array_sinh_vien')->get();

        // $array_lop = Lop::query()
        // ->selectRaw('lop.ma, lop.ten, COUNT(sinh_vien.ma_lop) as so_luong_sinh_vien')
        // ->leftJoin('sinh_vien','sinh_vien.ma_lop','lop.ma')
        // ->groupBy('lop.ma')
        // ->get();

    	return view("lop.view_all",[
    		'array_lop' => $array_lop
    	]);
    }
    public function view_insert()
    {
    	return view("lop.view_insert");
    }
    public function process_insert(Request $rq)
    {
    	// $lop = new Lop();
    	// $lop->ten = $rq->ten;
    	// $lop->save();

    	Lop::create($rq->all());

    	return redirect()->route('lop.view_all');
    }
    public function view_update($ma)
    {
    	// $lop = Lop::where('ma','=',$ma)->first();

    	$lop = Lop::find($ma);

    	return view("lop.view_update",[
    		'lop' => $lop
    	]);
    }
    public function process_update($ma, Request $rq)
    {
    	// $lop = Lop::find($ma);
    	// $lop->ten = $rq->ten;
    	// $lop->save();

    	// Lop::find($ma)->update([
    	// 	'ten' => $rq->ten
    	// ]);

    	Lop::find($ma)->update($rq->all());
    }
    public function delete($ma)
    {
    	// $lop = Lop::find($ma);
    	// $lop->delete();

    	Lop::find($ma)->delete();
    }
    public function view_array_sinh_vien_by_lop($ma)
    {
        $array_sinh_vien = Lop::find($ma)->array_sinh_vien;
        return view('view_array_sinh_vien_by_lop',compact('array_sinh_vien'));
    }
    public function view_lop_with_so_luong_sinh_vien()
    {
        $array = Lop::withCount('array_sinh_vien')->get();
        return view('lop.view_lop_with_so_luong_sinh_vien',compact('array'));
    }
    public function thong_ke_truot_excel()
    {
        $ngay_hom_nay = date('d_m_Y');
        return (new ThongKeTruotExportExcel)->download("thong_ke_truot_excel_$ngay_hom_nay.xlsx");
    }
    public function thong_ke_truot_pdf()
    {
        $ngay_hom_nay = date('d_m_Y');
        $array_lop = Lop::withCount('array_sinh_vien')->get();
        $pdf = PDF::loadView('lop.view_all', compact('array_lop'));
        return $pdf->download("lop_view_all.pdf");
    }
    public function thong_ke_truot_chart()
    {
        $array = Lop::query()
        ->select('lop.ma','lop.ten')
        ->selectRaw('
        (
            select count(*) 
            from diem 
            join sinh_vien as sv on sv.ma = diem.ma_sinh_vien 
            where sv.ma_lop = lop.ma and diem.diem < 5
        ) as so_lan_truot,
        (
            select count(DISTINCT diem.ma_sinh_vien) 
            from diem 
            join sinh_vien as sv on sv.ma = diem.ma_sinh_vien 
            where sv.ma_lop = lop.ma and diem.diem < 5
        ) as so_sinh_vien_truot
        ')
        ->leftjoin('sinh_vien','sinh_vien.ma_lop','lop.ma')
        ->groupBy('lop.ma')
        ->get();
        $array_lop =  array_column($array->toArray(), 'ten');  
        $array_so_lan_truot =  array_column($array->toArray(), 'so_lan_truot');  
        $array_so_sinh_vien_truot =  array_column($array->toArray(), 'so_sinh_vien_truot');  

        return view('lop.thong_ke_truot_chart',compact('array_lop','array_so_lan_truot','array_so_sinh_vien_truot'));
    }
}

resources/views/lop/thong_ke_truot_chart.blade.php
<div id="container" style="width:100%; height:400px;"></div>
<script src="{{ asset('js/highcharts.js') }}"></script>
<script type="text/javascript">
@php
$js_array_lop                = json_encode($array_lop);
$js_array_so_lan_truot       = json_encode($array_so_lan_truot);
$js_array_so_sinh_vien_truot = json_encode($array_so_sinh_vien_truot);
@endphp
var array_lop = {!! $js_array_lop !!};
var array_so_lan_truot = {!! $js_array_so_lan_truot !!};
var array_so_sinh_vien_truot = {!! $js_array_so_sinh_vien_truot !!};
Highcharts.chart('container', {
    chart: {
        zoomType: 'xy'
    },
    title: {
        text: 'Thống kê trượt'
    },
    xAxis: [{
        categories: array_lop,
        crosshair: true
    }],
    yAxis: [{ // Primary yAxis
    	allowDecimals: false,
        labels: {
            format: '{value} bạn',
            style: {
                color: Highcharts.getOptions().colors[1]
            }
        },
        title: {
            text: 'Số Sinh Viên Trượt',
            style: {
                color: Highcharts.getOptions().colors[1]
            }
        }
    }, { // Secondary yAxis
    	allowDecimals: false,
        title: {
            text: 'Số Lần Trượt',
            style: {
                color: Highcharts.getOptions().colors[0]
            }
        },
        labels: {
            format: '{value} lần',
            style: {
                color: Highcharts.getOptions().colors[0]
            }
        },
        opposite: true
    }],
    tooltip: {
        shared: true
    },
    legend: {
        layout: 'vertical',
        align: 'center',
        x: 0,
        verticalAlign: 'top',
        y: 50,
        floating: true,
        backgroundColor:
            Highcharts.defaultOptions.legend.backgroundColor || // theme
            'rgba(255,255,255,0.25)'
    },
    series: [{
        name: 'Số Sinh Viên Trượt',
        type: 'column',
        yAxis: 1,
        data: array_so_sinh_vien_truot,
        tooltip: {
            valueSuffix: ' bạn'
        }

    }, {
        name: 'Số Lần Trượt',
        type: 'spline',
        data: array_so_lan_truot,
        tooltip: {
            valueSuffix: ' lần'
        }
    }]
});
</script>

resources/views/lop/view_all.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">
	body {
		font-family: DejaVu Sans;
	}
	</style>
</head>
<body>

<a href="{{ route('lop.view_insert') }}">
	Thêm
</a>
<br>
<a href="{{ route('lop.thong_ke_truot_excel') }}">
	Thống kê sinh viên trượt theo lớp theo Excel
</a>
<br>
<a href="{{ route('lop.thong_ke_truot_pdf') }}">
	Thống kê sinh viên trượt theo lớp theo PDF
</a>
<br>
<a href="{{ route('lop.thong_ke_truot_chart') }}">
	Thống kê sinh viên trượt theo lớp theo biểu đồ
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Số lượng sinh viên</th>
		<th>Xem sinh viên lớp này</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array_lop as $lop)
		<tr>
			<td>
				{{ $lop->ma }}
			</td>
			<td>
				{{ $lop->ten }}
			</td>
			<td>
				{{ $lop->so_luong_sinh_vien }}
			</td>
			<td>
				<a href="{{ route('lop.view_array_sinh_vien_by_lop',['ma' => $lop->ma]) }}">
					Xem sinh viên
				</a>
			</td>
			<td>
				<a href="{{ route('lop.view_update',['ma' => $lop->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('lop.delete',['ma' => $lop->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>
</body>
</html>

resources/views/lop/view_insert.blade.php
<form action="{{ route('lop.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	<button>Thêm</button>
</form>

resources/views/lop/view_lop_with_so_luong_sinh_vien.blade.php
<table border="1" width="100%">
	<tr>
		<th>Mã Lớp</th>
		<th>Tên Lớp</th>
		<th>Số Lượng Sinh Viên</th>
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>
				{{ $each->ma }}
			</td>
			<td>
				{{ $each->ten }}
			</td>
			<td>
				{{ $each->array_sinh_vien_count }}
			</td>
		</tr>
	@endforeach
</table>

resources/views/lop/view_update.blade.php
<form action="{{ route('lop.process_update',['ma' => $lop->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $lop->ten }}">
	<br>
	<button>Sửa</button>
</form>