routes/web.php
<?php


Route::get('view_lop_with_so_luong_sinh_vien','LopController@view_lop_with_so_luong_sinh_vien');

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');

	$controller = "LopController";
	Route::group(["prefix" => "lop","as" => "lop."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
		
		Route::get("view_array_sinh_vien_by_lop/{ma}","$controller@view_array_sinh_vien_by_lop")->name("view_array_sinh_vien_by_lop");

		Route::get("thong_ke_truot_excel","$controller@thong_ke_truot_excel")->name("thong_ke_truot_excel");
		Route::get("thong_ke_truot_pdf","$controller@thong_ke_truot_pdf")->name("thong_ke_truot_pdf");
		Route::get("thong_ke_truot_chart","$controller@thong_ke_truot_chart")->name("thong_ke_truot_chart");
	});

	$controller = "SinhVienController";
	Route::group(["prefix" => "sinh_vien","as" => "sinh_vien."],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");

		// form thêm bằng Excel
		Route::get("view_insert_excel","$controller@view_insert_excel")->name("view_insert_excel");
		Route::post("process_insert_excel","$controller@process_insert_excel")->name("process_insert_excel");

		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");
	});

	$controller = "DiemController";
	Route::group(["prefix" => "diem","as" => "diem."],function() use ($controller){
		Route::get("","$controller@chon_lop_va_mon")->name("chon_lop_va_mon");
		Route::post("xem_diem","$controller@xem_diem")->name("xem_diem");
		Route::post("cap_nhat_diem","$controller@cap_nhat_diem")->name("cap_nhat_diem");
	});
});

Route::get('test','Controller@test');
Route::get('show','Controller@show');
Route::post('post_test','Controller@post_test')->name('post_test');

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
    use Notifiable;
    protected $table = 'sinh_vien';
    public $timestamps = false;
    protected $fillable = [
    	'ho',
    	'ten',
    	'ngay_sinh',
        'email',
    	'gioi_tinh',
    	'ma_lop',
    ];
    protected $primaryKey = 'ma';
    public function lop()
    {
        return $this->belongsTo('App\Models\Lop','ma_lop');
    }
}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Lop;
use App\Models\SinhVien;
use App\Http\Requests\SinhVienRequest;
use App\Notifications\NewStudent;
use Notification;
use App\Imports\SinhVienImport;
use Maatwebsite\Excel\Facades\Excel;

class SinhVienController extends Controller
{
    protected $table = 'sinh_vien';
    public function view_all(Request $rq)
    {
        $tim_kiem_ten = $rq->tim_kiem_ten; 
    	$array_sinh_vien = SinhVien::where('ten','like',"%$tim_kiem_ten%")->with('lop')->paginate(10);

    	return view("$this->table.view_all",[
            "array_sinh_vien" => $array_sinh_vien,
            "tim_kiem_ten"    => $tim_kiem_ten,
    	]);
    }
    public function view_insert()
    {
        $array_lop = Lop::get();
    	return view("$this->table.view_insert",[
            'array_lop' => $array_lop
        ]);
    }
    public function process_insert(Request $rq)
    {
    	$sinh_vien = SinhVien::create($rq->all());
        
        $sinh_vien->notify(new NewStudent($sinh_vien));

    	// return redirect()->route("$this->table.view_all");
    }
    public function view_update($ma)
    {
    	$sinh_vien = SinhVien::find($ma);
        $array_lop = Lop::get();

    	return view("$this->table.view_update",[
    		"sinh_vien" => $sinh_vien,
            "array_lop" => $array_lop,
    	]);
    }
    public function process_update($ma, SinhVienRequest $rq)
    {
    	SinhVien::find($ma)->update($rq->all());
    }
    public function delete($ma)
    {
    	SinhVien::find($ma)->delete();
    }
    public function view_insert_excel()
    {
        return view('sinh_vien.view_insert_excel');
    }
    public function process_insert_excel(Request $rq)
    {
        Excel::import(new SinhVienImport, $rq->file_excel);
    }

}

resources/views/sinh_vien/view_all.blade.php
<h1>
	<a href="{{ route('sinh_vien.view_insert_excel') }}">
		Thêm bằng Excel
	</a>
</h1>
<a href="{{ route('sinh_vien.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<caption>
		<form>
			Tìm kiếm tên
			<input type="search" name="tim_kiem_ten" value="{{ $tim_kiem_ten }}">
		</form>
	</caption>
	<tr>
		<th>Mã</th>
		<th>Họ</th>
		<th>Tên</th>
		<th>Ngày sinh</th>
		<th>Giới tính</th>
		<th>Tên lớp</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ma }}
			</td>
			<td>
				{{ $sinh_vien->ho }}
			</td>
			<td>
				{{ $sinh_vien->ten }}
			</td>
			<td>
				{{ $sinh_vien->ngay_sinh }}
			</td>
			<td>
				{{ $sinh_vien->gioi_tinh }}
			</td>
			<td>
				{{ $sinh_vien->lop->ten }}
			</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.delete',['ma' => $sinh_vien->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>
{{ $array_sinh_vien->links() }}

resources/views/sinh_vien/view_insert.blade.php
{{-- @php
	dd(old());
@endphp --}}
<style type="text/css">
.span_error{
	color: red;
}
.input_error{
	border: 1px solid red;
}
</style>
<form action="{{ route('sinh_vien.process_insert') }}" method="post">
	{{ csrf_field() }}
	Họ
	<input type="text" name="ho" 
	@if (!$errors->has('ho'))
	value="{{ old('ho') }}"
	@else
		class="input_error" 
	@endif
	>
	<span class="span_error">
		{{ $errors->first('ho') }}
	</span>
	<br>
	Tên
	<input type="text" name="ten">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh">
	@if ($errors->first('ngay_sinh'))
		<span class="span_error">
			{{ $errors->first('ngay_sinh') }}
		</span>
	@endif
	<br>
	Email
	<input type="email" name="email" 
	@if (empty($errors->has('email')))
		value="{{ old('email') }}" 
	@endif>
	@if ($errors->first('email'))
		<span class="span_error">
			{{ $errors->first('email') }}
		</span>
	@endif
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1" @if (old('gioi_tinh') == 1) checked @endif>Nữ
	<input type="radio" name="gioi_tinh" value="0">Nam
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}"
			@if (old('ma_lop') == $lop->ma)
				selected 
			@endif
			>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	@if ($errors->first('ma_lop'))
		{{ $errors->first('ma_lop') }}
	@endif
	<br>
	<button>Thêm</button>
</form>

resources/views/sinh_vien/view_insert_excel.blade.php
<form action="{{ route('sinh_vien.process_insert_excel') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	Chọn file Excel
	<input type="file" name="file_excel" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
	<button>Thêm</button>
</form>

resources/views/sinh_vien/view_update.blade.php
<form action="{{ route('sinh_vien.process_update',['ma' => $sinh_vien->ma]) }}" method="post">
	{{ csrf_field() }}
	Họ
	<input type="text" name="ho" value="{{ $sinh_vien->ho }}">
	<br>
	Tên
	<input type="text" name="ten" value="{{ $sinh_vien->ten }}">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh" value="{{ $sinh_vien->ngay_sinh }}">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1" 
	@if ($sinh_vien->gioi_tinh==1)
		checked 
	@endif>Nữ
	<input type="radio" name="gioi_tinh" value="0" 
	@if ($sinh_vien->gioi_tinh==0)
		checked 
	@endif>Nam
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}"
			@if ($lop->ma == $sinh_vien->ma_lop)
				selected 
			@endif
			>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Sửa</button>
</form>